// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AiReview struct {
	ID           string `json:"id"`
	SubmissionID string `json:"submission_id"`
	Feedback     string `json:"feedback"`
	// 0-100 optional
	Score       sql.NullInt32  `json:"score"`
	ReviewAgent sql.NullString `json:"review_agent"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Assignment struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	// easy | medium | hard
	Difficulty string         `json:"difficulty"`
	Tags       sql.NullString `json:"tags"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Submission struct {
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	AssignmentID string `json:"assignment_id"`
	Code         string `json:"code"`
	Language     string `json:"language"`
	// pending | running | passed | failed
	Status    sql.NullString `json:"status"`
	RuntimeMs sql.NullInt32  `json:"runtime_ms"`
	MemoryKb  sql.NullInt32  `json:"memory_kb"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type TestCase struct {
	ID             string       `json:"id"`
	AssignmentID   string       `json:"assignment_id"`
	Input          string       `json:"input"`
	ExpectedOutput string       `json:"expected_output"`
	IsHidden       sql.NullBool `json:"is_hidden"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type User struct {
	ID           string       `json:"id"`
	Email        string       `json:"email"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
