// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateAIReview(ctx context.Context, arg CreateAIReviewParams) (AiReview, error)
	CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAIReview(ctx context.Context, id string) error
	DeleteAssignment(ctx context.Context, id string) error
	DeleteSubmission(ctx context.Context, id string) error
	DeleteTestCase(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetAIReview(ctx context.Context, id string) (AiReview, error)
	GetAIReviewsBySubmission(ctx context.Context, submissionID string) ([]AiReview, error)
	GetAssignment(ctx context.Context, id string) (Assignment, error)
	GetSubmission(ctx context.Context, id string) (Submission, error)
	GetSubmissionsByAssignment(ctx context.Context, assignmentID string) ([]Submission, error)
	GetSubmissionsByUser(ctx context.Context, userID string) ([]Submission, error)
	GetTestCase(ctx context.Context, id string) (TestCase, error)
	GetTestCasesByAssignment(ctx context.Context, assignmentID string) ([]TestCase, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListAssignments(ctx context.Context) ([]Assignment, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateAIReview(ctx context.Context, arg UpdateAIReviewParams) (AiReview, error)
	UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (Assignment, error)
	UpdateSubmission(ctx context.Context, arg UpdateSubmissionParams) (Submission, error)
	UpdateTestCase(ctx context.Context, arg UpdateTestCaseParams) (TestCase, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
