// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: question.sql

package db

import (
	"context"
	"database/sql"
)

const createQuestion = `-- name: CreateQuestion :one
insert into questions (id, title, description, difficulty, tags) values ($1, $2, $3, $4, $5) returning id, title, description, difficulty, tags, created_at, updated_at
`

type CreateQuestionParams struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Difficulty  string         `json:"difficulty"`
	Tags        sql.NullString `json:"tags"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.Tags,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
delete from questions where id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, id)
	return err
}

const getQuestion = `-- name: GetQuestion :one
select id, title, description, difficulty, tags, created_at, updated_at from questions where id = $1
`

func (q *Queries) GetQuestion(ctx context.Context, id string) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuestions = `-- name: ListQuestions :many
select id, title, description, difficulty, tags, created_at, updated_at from questions order by created_at desc
`

func (q *Queries) ListQuestions(ctx context.Context) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Question{}
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestion = `-- name: UpdateQuestion :one
update questions set title = $2, description = $3, difficulty = $4, tags = $5 where id = $1 returning id, title, description, difficulty, tags, created_at, updated_at
`

type UpdateQuestionParams struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Difficulty  string         `json:"difficulty"`
	Tags        sql.NullString `json:"tags"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, updateQuestion,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Difficulty,
		arg.Tags,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
