// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AiReview struct {
	ID           string `json:"id"`
	SubmissionID string `json:"submission_id"`
	Feedback     string `json:"feedback"`
	// 0-100 optional
	Score       sql.NullInt32  `json:"score"`
	ReviewAgent sql.NullString `json:"review_agent"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Discussion struct {
	ID         string       `json:"id"`
	QuestionID string       `json:"question_id"`
	UserID     string       `json:"user_id"`
	Content    string       `json:"content"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Editorial struct {
	ID         string       `json:"id"`
	QuestionID string       `json:"question_id"`
	Content    string       `json:"content"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Question struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	// easy | medium | hard
	Difficulty string         `json:"difficulty"`
	Tags       sql.NullString `json:"tags"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type QuestionSection struct {
	ID         string        `json:"id"`
	QuestionID string        `json:"question_id"`
	Title      string        `json:"title"`
	Content    string        `json:"content"`
	Order      sql.NullInt32 `json:"order"`
}

type Solution struct {
	ID         string       `json:"id"`
	QuestionID string       `json:"question_id"`
	UserID     string       `json:"user_id"`
	Content    string       `json:"content"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Submission struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	QuestionID string `json:"question_id"`
	Code       string `json:"code"`
	Language   string `json:"language"`
	// pending | running | passed | failed
	Status    sql.NullString `json:"status"`
	RuntimeMs sql.NullInt32  `json:"runtime_ms"`
	MemoryKb  sql.NullInt32  `json:"memory_kb"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type TestCase struct {
	ID             string       `json:"id"`
	QuestionID     string       `json:"question_id"`
	Input          string       `json:"input"`
	ExpectedOutput string       `json:"expected_output"`
	IsHidden       sql.NullBool `json:"is_hidden"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type User struct {
	ID           string       `json:"id"`
	Email        string       `json:"email"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
